export const indice = ({
  personas: {
    colormap: [
      [0, "#feebe2"],
      [50, "#fbb4b9"],
      [100, "#f768a1"],
      [200, "#c51b8a"],
      [500, "#7a0177"],
    ],
    nombre: "Número de habitantes",
    ayuda: "número de personas",
    format: ".0f",
  },
  personas_por_hectarea: {
    colormap: [
      [0, "#feebe2"],
      [50, "#fbb4b9"],
      [100, "#f768a1"],
      [150, "#c51b8a"],
      [200, "#7a0177"],
    ],
    nombre: "Densidad poblacional",
    ayuda: "número de personas por hectárea",
    format: ".0f",
  },
  dependencia_economica: {
    colormap: [
      [75, "#bfdae2"],
      [100, "#94b8cd"],
      [125, "#7495b8"],
      [150, "#60709f"],
      [175, "#584b81"],
    ],
    nombre: "Dependencia económica",
    ayuda: "número de personas que no trabajan por 100 personas ocupadas",
    format: ".0f",
  },
  porcentaje_menor20: {
    colormap: [
      [0.2, "#f6eff7"],
      [0.3, "#bdc9e1"],
      [0.4, "#67a9cf"],
      [0.5, "#1c9099"],
      [0.6, "#016c59"],
    ],
    nombre: "Porcentaje de jóvenes",
    ayuda: "número de personas menores a 20 años por cada 100 habitantes",
    format: ".0%",
  },
  porcentaje_60omas: {
    colormap: [
      [0.05, "#f1eef6"],
      [0.1, "#bdc9e1"],
      [0.15, "#74a9cf"],
      [0.2, "#2b8cbe"],
      [0.25, "#045a8d"],
    ],
    nombre: "Porcentaje de adultos mayores",
    ayuda: "número de personas mayores a 60 años por cada 100 habitantes",
    format: ".0%",
  },
  masculinidad: {
    colormap: [
      [60, "#7b3294"],
      [80, "#c2a5cf"],
      [100, "#f7f7f7"],
      [120, "#a6dba0"],
      [140, "#008837"],
    ],
    nombre: "Índice de masculinidad",
    ayuda: "número de hombres por 100 mujeres",
    format: ".0f",
  },
  educacion_superior: {
    colormap: [
      [0.1, "#f0f9e8"],
      [0.2, "#bae4bc"],
      [0.3, "#7bccc4"],
      [0.4, "#43a2ca"],
      [0.5, "#0868ac"],
    ],
    nombre: "Porcentaje que terminó la educación superior",
    ayuda: "porcentaje que terminó la educación superior",
    format: ".0%",
  },
  poblacion_migrante: {
    colormap: [
      [0.1, "#d9e2d6"],
      [0.25, "#c3caa7"],
      [0.4, "#bcae76"],
      [0.55, "#bd8d4d"],
      [0.7, "#c06733"],
    ],
    nombre: "Porcentaje de inmigrantes",
    ayuda: "porcentaje de personas que nacieron en otro municipio o país",
    format: ".0%",
  },
  ocupados_empleados: {
    colormap: [
      [0.15, "#edf8fb"],
      [0.3, "#b3cde3"],
      [0.45, "#8c96c6"],
      [0.6, "#8856a7"],
      [0.75, "#810f7c"],
    ],
    nombre: "Porcentaje de empleados",
    ayuda: "porcentaje de ocupados con un empleo",
    format: ".0%",
  },
  ocupados_cuentapropistas: {
    colormap: [
      [0.25, "#edf8fb"],
      [0.35, "#b3cde3"],
      [0.45, "#8c96c6"],
      [0.55, "#8856a7"],
      [0.65, "#810f7c"],
    ],
    nombre: "Porcentaje de trabajadores a cuenta propia",
    ayuda: "porcentaje de ocupados que trabajan a cuenta propia",
    format: ".0%",
  },
  poblacion_agricultura: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.1, "#dccda4"],
      [0.2, "#dfb57d"],
      [0.3, "#e5985f"],
      [0.4, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en agricultura",
    ayuda: "porcentaje de ocupados en agricultura",
    format: ".0%",
  },
  poblacion_comercio: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.1, "#dccda4"],
      [0.2, "#dfb57d"],
      [0.3, "#e5985f"],
      [0.4, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en comercio",
    ayuda: "porcentaje de ocupados que trabajan en comercio",
    format: ".0%",
  },
  poblacion_manufactura: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.075, "#dccda4"],
      [0.15, "#dfb57d"],
      [0.225, "#e5985f"],
      [0.3, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en manufactura",
    ayuda: "porcentaje de ocupados en manufactura",
    format: ".0%",
  },
  poblacion_transporte: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.05, "#dccda4"],
      [0.1, "#dfb57d"],
      [0.15, "#e5985f"],
      [0.2, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en transporte",
    ayuda: "porcentaje de ocupados en transporte",
    format: ".0%",
  },
  poblacion_construccion: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.05, "#dccda4"],
      [0.1, "#dfb57d"],
      [0.15, "#e5985f"],
      [0.2, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en construcción",
    ayuda: "porcentaje de ocupados en construcción",
    format: ".0%",
  },
  poblacion_alojamientoycomida: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.05, "#dccda4"],
      [0.1, "#dfb57d"],
      [0.15, "#e5985f"],
      [0.2, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en alojamiento y comida",
    ayuda: "porcentaje de ocupados en alojamiento y comida",
    format: ".0%",
  },
  poblacion_enseñanza: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.04, "#dccda4"],
      [0.08, "#dfb57d"],
      [0.12, "#e5985f"],
      [0.16, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en educación",
    ayuda: "porcentaje de ocupados en educación",
    format: ".0%",
  },
  poblacion_saludyasistencia: {
    colormap: [
      [0.0, "#e2e1cf"],
      [0.04, "#dccda4"],
      [0.08, "#dfb57d"],
      [0.12, "#e5985f"],
      [0.16, "#ec774d"],
    ],
    nombre: "Porcentaje de trabajadores en salud",
    ayuda: "porcentaje de ocupados en salud y asistencia",
    format: ".0%",
  },
  viviendas_desocupadas: {
    colormap: [
      [0.0, "#cfc8e2"],
      [0.05, "#c6a7c2"],
      [0.1, "#bd8898"],
      [0.15, "#aa6c69"],
      [0.2, "#8b583a"],
    ],
    nombre: "Porcentaje de viviendas desocupadas",
    ayuda: "porcentaje de viviendas particulares desocupadas",
    format: ".0%",
  },
  viviendas_alquiladas_anticretico: {
    colormap: [
      [0.0, "#cfc8e2"],
      [0.15, "#c6a7c2"],
      [0.3, "#bd8898"],
      [0.45, "#aa6c69"],
      [0.6, "#8b583a"],
    ],
    nombre: "Porcentaje de viviendas alquiladas",
    ayuda: "porcentaje de viviendas particulares alquiladas o en anticrético",
    format: ".0%",
  },
  viviendas_energiaelectrica_serviciopublico: {
    colormap: [
      [0.6, "#e2d9c1"],
      [0.7, "#b6c8ac"],
      [0.8, "#84b7a7"],
      [0.9, "#57a2ad"],
      [1, "#4989af"],
    ],
    nombre: "Porcentaje de viviendas con energía eléctrica",
    ayuda: "porcentaje de viviendas particulares con energía eléctrica",
    format: ".0%",
  },
  viviendas_agua_cañería: {
    colormap: [
      [0.6, "#e2d9c1"],
      [0.7, "#b6c8ac"],
      [0.8, "#84b7a7"],
      [0.9, "#57a2ad"],
      [1, "#4989af"],
    ],
    nombre: "Porcentaje de viviendas con agua de cañería",
    ayuda: "porcentaje de viviendas particulares con agua de cañería",
    format: ".0%",
  },
  viviendas_desague_alcantarillado: {
    colormap: [
      [0.6, "#e2d9c1"],
      [0.7, "#b6c8ac"],
      [0.8, "#84b7a7"],
      [0.9, "#57a2ad"],
      [1, "#4989af"],
    ],
    nombre: "Porcentaje de viviendas con alcantarillado",
    ayuda: "porcentaje de viviendas particulares con alcantarillado",
    format: ".0%",
  },
  viviendas_combustible_gascañería: {
    colormap: [
      [0, "#e2d9c1"],
      [0.25, "#b6c8ac"],
      [0.5, "#84b7a7"],
      [0.75, "#57a2ad"],
      [1, "#4989af"],
    ],
    nombre: "Porcentaje de viviendas con gas",
    ayuda: "porcentaje de viviendas particulares con gas de cañería",
    format: ".0%",
  },
  viviendas_tics_internet: {
    colormap: [
      [0.68, "#e2d9c1"],
      [0.76, "#b6c8ac"],
      [0.84, "#84b7a7"],
      [0.92, "#57a2ad"],
      [1, "#4989af"],
    ],
    nombre: "Porcentaje de viviendas con internet",
    ayuda: "porcentaje de viviendas particulares con internet fijo o móvil",
    format: ".0%",
  },
});